server:
  port: 8792
spring:
  datasource:
    username: user
    password: pwd
    url: jdbc:mysql://localhost:3306/believe?characterEncoding=utf8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true